#reference "tools/Cake.Unity/lib/net46/Cake.Unity.dll"
#load "UnityBuildTargetType.cs"
#load "UnityEditorToolSettings.cs"
#load "UnityEditorToolArguments.cs"
#load "UnityEditorTool.cs"
#load "UnityBuildActions.cs"
